### ISSUE TITLE
Missing code coverage

### ISSUE THREAD

**Issue by ghost** [dbacinski/Android-Testing-In-Kotlin#3]
Hi,
as your repo would be about writing unit tests with clean MVP architecture, I think that you would find useful using code coverage tools. In Android Studio there's an option to run tests with coverage, but some guys uses also [JaCoCo](jacoco-android-gradle-plugin) library. 

Check: [Code coverage on Android with JaCoCo](https://blog.gouline.net/code-coverage-on-android-with-jacoco-92ec90c9355e#.uzjupf1rf)

For Github repos purposes, you can check [Codecov](https://github.com/integrations/codecov) or [Coveralls](https://github.com/integrations/coveralls).

Hope it will help.
Cheers

**Comment by dbacinski** [comment]
Code coverage report is configured using Codecov, but it has stopped working with BuddyBuild free plan. 

https://codecov.io/gh/dbacinski/Android-Testing-With-Kotlin

I will enable it again after migrating to Circle CI https://github.com/dbacinski/Android-Testing-With-Kotlin/issues/2

**Comment by dbacinski** [comment]
Done
